// Bilingual content for Pakman site. Keep all copy here so EN/AR pages stay in sync.

export type Lang = "en" | "ar";

export const content = {
  en: {
    dir: "ltr" as const,
    lang: "en",
    htmlLang: "en",
    introTagline: "Packaging Solutions",
    nav: {
      home: "Home",
      about: "About",
      products: "Products",
      solutions: "Solutions",
      work: "Our Work",
      clients: "Clients",
      contact: "Contact",
      cta: "Request a Quote",
      switchLang: "العربية",
      switchHref: "/ar",
    },
    hero: {
      eyebrow: "Pakman Packaging Solutions",
      title1: "Premium Packaging",
      title2: "for Restaurants and Cafés",
      sub: "Complete custom packaging solutions for food businesses that care about presentation, quality and customer experience.",
      body: "From coffee cups and paper bags to burger boxes, food containers, napkins, labels and takeaway packaging, Pakman helps restaurants and cafés serve their products with a professional brand presence.",
      ctaPrimary: "Request a Quote",
      ctaSecondary: "View Products",
      trust: "Founded in Jeddah, Saudi Arabia in 2024",
    },
    clients: {
      eyebrow: "Clients",
      title: "Trusted By Leading Food Brands",
      text: "We proudly provide premium packaging solutions for restaurants, cafés and food brands serving thousands of customers every day.",
    },
    about: {
      eyebrow: "About",
      title: "About Pakman",
      body1:
        "Pakman Packaging Solutions is a Saudi company founded in Jeddah, Saudi Arabia in 2024. We specialize in complete packaging solutions for restaurants, cafés, bakeries, catering companies and food brands.",
      body2:
        "Our mission is to help food businesses present their products professionally through high quality packaging that protects the product, strengthens the brand and improves the customer experience.",
      title2: "An Ecosystem Built Around Food Businesses",
      body3:
        "From coffee cups and paper bags to custom printed boxes, labels and takeaway packaging, Pakman provides a complete ecosystem designed around the daily needs of food businesses.",
      body4:
        "We work alongside our clients from idea to delivery, helping them choose the right materials, sizes, finishing and branding applications so every package they hand a customer feels like an extension of their brand.",
    },
    products: {
      eyebrow: "Products",
      title: "Complete Restaurant Packaging Solutions",
      list: [
        "Coffee Cups",
        "Cold Drink Cups",
        "Cup Lids",
        "Cup Sleeves",
        "Paper Bags",
        "Burger Boxes",
        "Sandwich Boxes",
        "Food Containers",
        "Salad Bowls",
        "Soup Bowls",
        "Plates",
        "Pizza Boxes",
        "Bakery Boxes",
        "Napkins",
        "Cutlery",
        "Labels",
        "Stickers",
        "Wrapping Paper",
        "Takeaway Bags",
        "Delivery Packaging",
        "Tissue Boxes",
        "Custom Printed Packaging",
      ],
    },
    solutions: {
      eyebrow: "Solutions",
      title: "Built for Every Food Business",
      cards: [
        { t: "Restaurants", d: "Packaging for dine in, takeaway and delivery operations." },
        { t: "Cafés", d: "Cups, sleeves, bags, labels and branded packaging for coffee concepts." },
        {
          t: "Bakeries",
          d: "Boxes, bags, stickers and wrapping paper for baked goods and desserts.",
        },
        {
          t: "Catering Companies",
          d: "Reliable packaging for events, meal service and professional food presentation.",
        },
        {
          t: "Cloud Kitchens",
          d: "Practical and branded packaging for delivery focused food businesses.",
        },
        { t: "Food Brands", d: "Custom packaging that helps food products look market ready." },
      ],
    },
    work: {
      eyebrow: "Our Work",
      title: "Packaging That Represents the Brand",
      text: "A visual gallery of packaging applications created for food businesses, including cups, paper bags, food boxes, labels, napkins and takeaway solutions.",
    },
    why: {
      eyebrow: "Why Pakman",
      title: "Why Food Businesses Choose Pakman",
      points: [
        "Complete restaurant packaging supply",
        "Custom branding and printing",
        "Food safe material options",
        "Flexible quantities",
        "Clean finishing",
        "Fast communication",
        "Reliable delivery",
        "Support from idea to final product",
      ],
    },
    quote: {
      eyebrow: "Request a Quote",
      title: "Request a Packaging Quote",
      text: "Tell us about your restaurant, café or food brand and our team will help you choose the right packaging solution.",
      fields: {
        name: "Full Name",
        company: "Company Name",
        type: "Business Type",
        phone: "Phone Number",
        email: "Email Address",
        products: "Packaging Products Needed",
        qty: "Estimated Quantity",
        message: "Message",
      },
      submit: "Send Request",
      note: "Our team replies within one business day.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Contact Pakman",
      location: "Jeddah, Al Rawdah District, Nahdat Al Nasr",
      phoneLabel: "Phone",
      phone: "+966 53 158 5759",
      emailLabel: "Email",
      email: "Info@pakman-mena.com",
      whatsapp: "WhatsApp",
    },
    locationSection: {
      title: "Our Headquarters",
      sub: "Visit Pakman in Jeddah, the heart of Saudi Arabia's hospitality and food scene.",
      company: "Pakman Headquarters",
      city: "Jeddah",
      district: "Al Rawdah District",
      area: "Nahdat Al Nasr",
      cta: "View on Google Maps",
      mapsUrl: "https://maps.app.goo.gl/KcoPSwf5fX6mQD7PA?g_st=ic",
    },
    footer: {
      title: "Pakman Packaging Solutions",
      text: "A Saudi packaging company providing complete custom packaging solutions for restaurants, cafés, bakeries, catering companies and food brands.",
      rights: "© 2026 Pakman Packaging Solutions. All rights reserved.",
      sectionsLabel: "Sections",
      contactLabel: "Contact",
    },
  },
  ar: {
    dir: "rtl" as const,
    lang: "ar",
    htmlLang: "ar",
    introTagline: "حلول التغليف",
    nav: {
      home: "الرئيسية",
      about: "من نحن",
      products: "المنتجات",
      solutions: "الحلول",
      work: "أعمالنا",
      clients: "العملاء",
      contact: "تواصل",
      cta: "طلب عرض سعر",
      switchLang: "English",
      switchHref: "/",
    },
    hero: {
      eyebrow: "باكمان لحلول التغليف",
      title1: "تغليف احترافي",
      title2: "للمطاعم والمقاهي",
      sub: "حلول تغليف مخصصة ومتكاملة للعلامات الغذائية التي تهتم بطريقة التقديم وجودة المنتج وتجربة العميل.",
      body: "من أكواب القهوة والأكياس الورقية إلى علب البرجر وعلب الطعام والمناديل والملصقات وتغليف التيك أواي، تساعد باكمان المطاعم والمقاهي على تقديم منتجاتها بحضور احترافي يعكس قيمة العلامة.",
      ctaPrimary: "طلب عرض سعر",
      ctaSecondary: "عرض المنتجات",
      trust: "شركة سعودية تأسست في جدة عام 2024",
    },
    clients: {
      eyebrow: "العملاء",
      title: "موثوق من علامات غذائية رائدة",
      text: "نفخر بتقديم حلول تغليف احترافية للمطاعم والمقاهي والعلامات الغذائية التي تخدم آلاف العملاء يومياً.",
    },
    about: {
      eyebrow: "من نحن",
      title: "من نحن",
      body1:
        "باكمان لحلول التغليف شركة سعودية تأسست في جدة عام 2024، متخصصة في تقديم حلول تغليف متكاملة للمطاعم والمقاهي والمخابز وشركات الإعاشة والعلامات الغذائية.",
      body2:
        "نؤمن بأن التغليف ليس مجرد وسيلة لحفظ المنتج، بل جزء أساسي من تجربة العميل وهوية العلامة التجارية. لذلك نوفر مجموعة متكاملة من حلول التغليف المصممة لتساعد العلامات الغذائية على الظهور بشكل احترافي وتقديم منتجاتها بأفضل صورة ممكنة.",
      title2: "منظومة متكاملة لقطاع الأغذية والمشروبات",
      body3:
        "من أكواب القهوة والأكياس الورقية إلى العلب المطبوعة والملصقات وحلول التيك أواي والتوصيل، تقدم باكمان منظومة متكاملة تلبي احتياجات قطاع الأغذية والمشروبات.",
      body4:
        "نعمل مع عملائنا من الفكرة حتى التسليم، ونساعدهم في اختيار الخامات والمقاسات والتشطيبات وتطبيقات الهوية، ليصبح كل تغليف يخرج باسمهم امتدادًا حقيقيًا لعلامتهم التجارية.",
    },
    products: {
      eyebrow: "المنتجات",
      title: "حلول متكاملة لتغليف المطاعم",
      list: [
        "أكواب القهوة",
        "أكواب المشروبات الباردة",
        "أغطية الأكواب",
        "أغلفة الأكواب",
        "أكياس ورقية",
        "علب برجر",
        "علب ساندويتش",
        "علب طعام",
        "علب سلطة",
        "علب شوربة",
        "أطباق",
        "علب بيتزا",
        "علب مخابز",
        "مناديل",
        "أدوات طعام",
        "ملصقات",
        "استكرات",
        "ورق تغليف",
        "أكياس تيك أواي",
        "تغليف التوصيل",
        "علب مناديل",
        "تغليف مطبوع مخصص",
      ],
    },
    solutions: {
      eyebrow: "الحلول",
      title: "مصمم لكل علامة غذائية",
      cards: [
        { t: "المطاعم", d: "تغليف مناسب للطلبات الداخلية والتيك أواي والتوصيل." },
        { t: "المقاهي", d: "أكواب وأغلفة وأكياس وملصقات وتغليف يحمل هوية المقهى." },
        { t: "المخابز", d: "علب وأكياس واستكرات وورق تغليف مخصص للمخبوزات والحلويات." },
        { t: "شركات الإعاشة", d: "تغليف موثوق للمناسبات والوجبات والتقديم الاحترافي." },
        { t: "المطابخ السحابية", d: "تغليف عملي واحترافي للعلامات التي تعتمد على التوصيل." },
        { t: "العلامات الغذائية", d: "تغليف مخصص يساعد المنتج على الظهور بشكل جاهز للسوق." },
      ],
    },
    work: {
      eyebrow: "أعمالنا",
      title: "تغليف يعكس هوية العلامة",
      text: "معرض بصري لتطبيقات التغليف التي تخدم العلامات الغذائية، ويشمل الأكواب والأكياس الورقية وعلب الطعام والملصقات والمناديل وحلول التيك أواي.",
    },
    why: {
      eyebrow: "لماذا باكمان",
      title: "لماذا تختار العلامات الغذائية باكمان",
      points: [
        "توريد متكامل لتغليف المطاعم",
        "تخصيص وطباعة حسب الهوية",
        "خيارات خامات آمنة للأغذية",
        "كميات مرنة",
        "تشطيب نظيف",
        "تواصل سريع",
        "تسليم موثوق",
        "دعم من الفكرة حتى المنتج النهائي",
      ],
    },
    quote: {
      eyebrow: "طلب عرض سعر",
      title: "اطلب عرض سعر للتغليف",
      text: "حدثنا عن مطعمك أو مقهاك أو علامتك الغذائية وسيساعدك فريقنا في اختيار حل التغليف المناسب.",
      fields: {
        name: "الاسم الكامل",
        company: "اسم الشركة",
        type: "نوع النشاط",
        phone: "رقم الجوال",
        email: "البريد الإلكتروني",
        products: "منتجات التغليف المطلوبة",
        qty: "الكمية المتوقعة",
        message: "الرسالة",
      },
      submit: "إرسال الطلب",
      note: "يرد فريقنا خلال يوم عمل واحد.",
    },
    contact: {
      eyebrow: "تواصل",
      title: "تواصل مع باكمان",
      location: "جدة، حي الروضة، نهضة النصر",
      phoneLabel: "الجوال",
      phone: "+966 53 158 5759",
      emailLabel: "البريد",
      email: "Info@pakman-mena.com",
      whatsapp: "واتساب",
    },
    locationSection: {
      title: "مقرنا الرئيسي",
      sub: "زورونا في جدة، قلب قطاع الضيافة والأغذية في المملكة العربية السعودية.",
      company: "المقر الرئيسي لباكمان",
      city: "جدة",
      district: "حي الروضة",
      area: "نهضة النصر",
      cta: "عرض على خرائط جوجل",
      mapsUrl: "https://maps.app.goo.gl/KcoPSwf5fX6mQD7PA?g_st=ic",
    },
    footer: {
      title: "باكمان لحلول التغليف",
      text: "شركة سعودية تقدم حلول تغليف مخصصة ومتكاملة للمطاعم والمقاهي والمخابز وشركات الإعاشة والعلامات الغذائية.",
      rights: "© 2026 باكمان لحلول التغليف. جميع الحقوق محفوظة.",
      sectionsLabel: "أقسام الموقع",
      contactLabel: "للتواصل",
    },
  },
} satisfies Record<Lang, unknown>;
